"""empty message

Revision ID: 1b768a981fa2
Revises: 724cc6dac386
Create Date: 2022-10-07 21:25:41.229938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b768a981fa2'
down_revision = '724cc6dac386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('route', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rates'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    # ### end Alembic commands ###
