"""empty message

Revision ID: 1dcd25061332
Revises: c6d2e830e693
Create Date: 2022-08-15 12:53:13.961196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcd25061332'
down_revision = 'c6d2e830e693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smsreports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('recepient', sa.String(length=64), nullable=True),
    sa.Column('retries', sa.String(length=64), nullable=True),
    sa.Column('sender', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smsreports'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smsreports')
    # ### end Alembic commands ###
