"""empty message

Revision ID: 2bfd4d34cad5
Revises: d46e8de99fdd
Create Date: 2022-11-05 09:27:49.494729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bfd4d34cad5'
down_revision = 'd46e8de99fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))

    with op.batch_alter_table('smsreports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smsreports', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
