"""empty message

Revision ID: 724cc6dac386
Revises: 52e093d4a0ba
Create Date: 2022-10-07 11:44:47.187668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724cc6dac386'
down_revision = '52e093d4a0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
