"""empty message

Revision ID: c6f859d14d4f
Revises: 929107d76c80
Create Date: 2022-08-14 01:32:06.547685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f859d14d4f'
down_revision = '929107d76c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    with op.batch_alter_table('phonebooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('phonebooks', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
